### ISSUE TITLE
dependency notes

### ISSUE THREAD

**Issue by JamesFrew** [SpatioTemporal/STAREMaster_py#21]
When installing the dependencies with `conda`:

- `argparse` appears to be a python-2-only package. It also appears to be unnecessary...
- `dask` installs `numpy` and `pandas`
- to load `pyhdf` you need to specify the `conda-forge` package repository.

Additional depencies:

- `filelock`
- `swig`

**Comment by NiklasPhabian** [comment]
ok. Should add conda install instructions and add the additional dependencies.
I am confused though as to why swig would be required. Likely just to install pystare?

Argparse is also python3 package and is required to parse the CLI options:
https://docs.python.org/3/library/argparse.html

**Comment by michaelleerilee** [comment]
SWIG is required for pystare.

**Comment by NiklasPhabian** [comment]
I think the installer should solve this. All dependencies should be installed automatically.
I have not looked at how this works with conda yet.
