### ISSUE TITLE
AttributeError: module 'pystare' has no attribute 'from_latlon2D'

### ISSUE THREAD

**Issue by JamesFrew** [SpatioTemporal/STAREMaster_py#22]
```
python3 create_sidecar_files.py --workers 4 --product MOD09 --file MOD09.A2019317.0815.006.2019319020759.hdf
Traceback (most recent call last):
  File "create_sidecar_files.py", line 123, in <module>
    create_sidecar(file_path=file_path,
  File "create_sidecar_files.py", line 18, in create_sidecar
    sidecar = products.mod09.create_sidecar(file_path, workers, cover_res, out_path)
  File "/Users/frew/Downloads/STAREMaster_py/products/mod09.py", line 26, in create_sidecar
    sids = conversions.latlon2stare(granule.lats, granule.lons, workers)
  File "/Users/frew/Downloads/STAREMaster_py/conversions.py", line 24, in latlon2stare
    sids = latlon2stare_dask(lats, lons, workers)
  File "/Users/frew/Downloads/STAREMaster_py/conversions.py", line 13, in latlon2stare_dask
    sids = xarray.apply_ufunc(pystare.from_latlon2D,
AttributeError: module 'pystare' has no attribute 'from_latlon2D'
```

**Comment by NiklasPhabian** [comment]
ah! Good you caught that. The function only exists on my fork and there is a pending pull request:
https://github.com/SpatioTemporal/pystare/pull/6

**Comment by NiklasPhabian** [comment]
You could now try to pull the latest version and try to install as:

Make virtualenv with virtualenvwrapper or your favorite alternative:
```
mkvirtualevironment staremaster_py
```

Install pystare from my fork:
```
pip3 install git+https://github.com/NiklasPhabian/pystare.git
```

and then install STAREMaster_py from a local cloned directory
```
pip3 install STAREMaster_py/
```

Or straight from github:
```
pip3 install git+https://github.com/SpatioTemporal/STAREMaster_py.git
```

**Comment by JamesFrew** [comment]
Works w/ your pystare.
 4 workers seems to be the sweet spot on my Mac (8 cores, 64G RAM):
```
$ time python3 create_sidecar_files.py --workers 4 --product MOD09 --file MOD09.A2019317.0815.006.2019319020759.hdf

real	0m11.244s
user	0m29.832s
sys	0m1.476s
```
Not bad!

**Comment by NiklasPhabian** [comment]
you got it to work!!!!  This fantastic!!

Yes; the sweetspot of 4 makes sense since for now I hardcoded the chunksize to 500 in track dimension ... since the track dimension 2030 for MOD09, more than 4 workers should not give a speedup.

> (8 cores, 64G RAM):
Nice flex

I feel like the dask speedup to lookup indices in parallel are dwarfed by the speedup of parallel processing several granules with multiprocessing (requires argument --parallel_files and specifying several granules after --files or a --folder)
