### ISSUE TITLE
VNP03DNB sidecars are huge

### ISSUE THREAD

**Issue by NiklasPhabian** [SpatioTemporal/STAREMaster_py#9]
VNP03DNB granules are about 50 MB with 14 variables+
The corresponding sidecar is around 300 MB with 4 variables

1. Might be an issue of how we write the sidecar netCDF? --> Appending?
2. Is there any kind of compression?
3. Are we using the wrong data types? 
lat/lon in the granule are 'float'
lat/lon in the sidecar are 'double
4. What's up with the chunking?
lat/lon granule:   :_ChunkSizes = 16U, 4064U; // uint
lat/lon sidecar:   :_ChunkSizes = 3248U, 4064U; // uint

**Comment by NiklasPhabian** [comment]
some quick testing seems to rule 1. out

**Comment by NiklasPhabian** [comment]
Probably an easy way to go about this is to write out each variable separately and see how much the size increases

**Comment by michaelleerilee** [comment]
Looking at a VNP03DNB file, i.e 
<pre>
ncdump -hs /Users/mrilee/LocalDownloads/GoogleChrome/VNP03DNB.A2019356.0000.001.2019356071101.nc
</pre>
I don't see any doubles, only float. There are many int as well, not sure about the number of bits at the moment. The deflation level is 5 for most variables. The data are chunked and shuffled.

So one index ( (i,j)->stare ) of int64 in the sidecar should be about twice the size of a float variable, before compression.

[Here's a link on chunking & deflating in NetCDF4.](https://www.unidata.ucar.edu/software/netcdf/workshops/2011/nc4chunking/index.html)

[And another on compression.](https://unidata.github.io/netcdf4-python/netCDF4/index.html#section9)

Chunks are partitions of the data, as you might guess, and seem more important for IO. A bit like an old fashioned record. Probably will have minimal impact on file size or compression.

Decompressing shows they're getting about a factor of 2 benefit from a deflation level of 5. To wit:

<pre>
(develop) twu4:tmp mrilee$ nccopy -d0 VNP03DNB.A2019356.0000.001.2019356071101.nc tmp.nc
(develop) twu4:tmp mrilee$ du -sm VNP03DNB.A2019356.0000.001.2019356071101.nc tmp.nc
48	NP03DNB.A2019356.0000.001.2019356071101.nc
113	tmp.nc
</pre>

I'd change the latlons to float and then compress. As a first step, you can try
<pre>
nccopy -d<target deflation level> src.nc tgt.nc
</pre>
to get a sense of how much compression might help the sidecar.

**Comment by NiklasPhabian** [comment]
VNP03DNB contain 3248x4064 (13 M) iFOVs, 
MOD09 2030x154 (3 M) iFOVs

Both in VNP03DNB and MOD09, lat/lon are floats, not doubles. Consequently, we should also set them as floats in the sidecar. 

Without zlib:
lat+lon as floats make up about 100 MB of the file size
lat+lon as double make up about 200 MB of the file size
SIDS make up 100 MB without

With zlib (at default complevel 4):
lat+lon come out as 30 MB, both for float and double
SIDs come out as 50 MB

The zlib (and lat/lon set to float), the sidecar is now 110 MB. Still bigger than the granule itself, but that seems to just be the nature of having a large number of int64 values.

I still need to verify the chunking. It bothers me that the granule chunks lat/lon differently than the sidecar.
